name: 'Start local Dash network'
description: 'Invokes mn-bootstrap to set up a local network for CI'
inputs:
  dapi-image-build-branch:
    description: 'dapi branch to be injected into mn-bootstrap'
  drive-image-build-branch:
    description: 'drive branch to be injected into mn-bootstrap'
  install-sdk-version:
    description: 'Dash SDK (DashJS) branch to be injected into mn-bootstrap'

runs:
  using: composite
  steps:
    - name: Set up tools
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci && npm link
    - name: Start local network
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        source bin/start-local-node.sh $GITHUB_WORKSPACE/package.json \
          --override-major-version=0 \
          --dapi-branch=${{ inputs.dapi-image-build-branch }} \
          --drive-branch=${{ inputs.drive-image-build-branch }} \
          --sdk-branch=${{ inputs.install-sdk-version }}
