name: 'Start Local Dash Node'
description: 'Invokes mn-bootstrap to set up a local node for CI'
inputs:
  dapi-branch:
    description: 'dapi branch to be injected into mn-bootstrap'
    default: $GITHUB_REF
  drive-branch:
    description: 'drive branch to be injected into mn-bootstrap'
    default: $GITHUB_REF
runs:
  using: "composite"
  steps:
    - name: Debug data
      shell: bash
      run: |
        echo "DAPI branch:" ${{ inputs.dapi-branch }}
        echo "Drive branch: " ${{ inputs.drive-branch }}
    - name: Set up tools
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci && npm link
    - name: Start local node
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "Starting local node..."
        source bin/start-local-node.sh $GITHUB_WORKSPACE/package.json \
          --override-major-version=0 \
          --dapi-branch=${{ inputs.dapi-branch }} \
          --drive-branch=${{ inputs.drive-branch }}
